DECLARE @StartTime DATETIME2 = SYSDATETIME()
DECLARE @EndTime DATETIME2 = SYSDATETIME()
SET @StartTime = SYSDATETIME()
SET @EndTime = SYSDATETIME()
PRINT('Area:' + CAST(DATEDIFF(MILLISECOND, @StartTime, @EndTime) AS VARCHAR) + 'ms')

/*
DECLARE @StartTime DATETIME2 = SYSDATETIME()
DECLARE @EndTime DATETIME2 = SYSDATETIME()


SET @StartTime = SYSDATETIME()

WAITFOR DELAY '00:00:02'

SET @EndTime = SYSDATETIME()
PRINT('Test 2s:' + CAST(DATEDIFF(MILLISECOND, @StartTime, @EndTime) AS VARCHAR) + 'ms')
*/
